# Basic
title: èƒ¡è±†ç§†
subtitle: ä¸ªäººåšå®¢
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººåšå®¢~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: hubeans
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Java / ç½‘ç«™
url: "http://hu12340.github.io"

# Comment
comment:
#     disqus: hu12340
# gitment: xxx // éœ€è¦ä¿®æ”¹ comments.htmlä¸­çš„client_idå’Œclient_secret
    gitment:
        enable: true # æ˜¯å¦å¼€å¯gitmentè¯„è®ºç³»ç»Ÿ
        mint: true #
        count: true # æ˜¯å¦æ˜¾ç¤ºè¯„è®ºæ•°
        lazy: true # æ‡’åŠ è½½ï¼Œè®¾ç½®ä¸ºtureæ—¶éœ€æ‰‹åŠ¨å±•å¼€è¯„è®º
        cleanly: true # æ˜¯å¦éšè—'Powered by ...'
        language:  # è¯­è¨€ï¼Œç½®ç©ºåˆ™éšä¸»é¢˜çš„è¯­è¨€
        github_user: hu12340 # Githubç”¨æˆ·å
        github_repo: blog-comment # åœ¨Githubæ–°å»ºä¸€ä¸ªä»“åº“ç”¨äºå­˜æ”¾è¯„è®ºï¼Œè¿™æ˜¯ä»“åº“å
        client_id: a110285c17681caa62b5 # æ³¨å†ŒOAuth Applicationæ—¶ç”Ÿæˆ
        client_secret: 2df00187c2eb685098fe8378ef06636af82d8590 # æ³¨å†ŒOAuth Applicationæ—¶ç”Ÿæˆ
        proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
        redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled
# uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    weibo: 5951657872
    github: hu12340
# zhihu: 
# juejin: xxx
#jianshu: 
# twitter: 
    mail: 15775960389@163.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: xxxx  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: xxxx  
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


